version: "3.4"

networks:
   dev:
      driver: bridge

services:
   app_db:
      image: postgres:latest
      container_name: app_db
      environment:
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=12345
         - POSTGRES_DB=TaskManager
      ports:
         - "5432:5432"
      restart: always
      volumes:
         - app_data:/var/lib/postgresql/data
      networks:
         - dev

volumes:
   app_data:
