name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0'

      - name: Install dependencies
        run: dotnet restore ./TaskManager/TaskManager/TaskManager.csproj  

      - name: Run tests
        run: dotnet test ./TaskManager/TaskManager.Tests/TaskManager.Tests.csproj --logger "trx;LogFileName=$(pwd)/TaskManager/TaskManager.Tests/TestReport/test_report.trx"

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: TestResults
          path: ./TaskManager/TaskManager.Tests/TestReport/test_report.trx

      - name: Clean the project
        run: dotnet clean ./TaskManager/TaskManager/TaskManager.csproj

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
      - name: Build Docker image
        run: docker build --no-cache -t arteam18/my-taskmanager:${{ github.sha }} -f TaskManager/TaskManager/Dockerfile .

      - name: Push Docker image to Docker Hub
        run: docker push arteam18/my-taskmanager:${{ github.sha }}
